linters-settings:
  gci:
    local-prefixes: github.com/open-amt-cloud-toolkit/console
  errorlint:
    errorf: true
  errcheck:
    check-type-assertions: true
    check-blank: false
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  funlen:
    lines: 100
    statements: 45
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 10
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - unnecessaryBlock
      - hugeParam
  gofumpt:
    extra-rules: true
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nestif:
    min-complexity: 4
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    # - depguard
    - dogsled
    # - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gci
    # - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - gofmt
    - gofumpt
    - goimports
    - mnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tparallel
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - wsl
    - whitespace

# disable:
#    - exhaustivestruct
#    - ifshort
#    - goheader
#    - prealloc
#    - testpackage
#    - wrapcheck

issues:
  exclude-rules:
    - path: integration-test
      linters:
        - paralleltest
        - godot
    - path: internal/controller/http
      linters:
        - godot
    - path: (.+)_test.go
      linters:
        - funlen
        - goerr113
  exclude-dirs:
    - docs
