services:
  # postgres:
  #   container_name: postgres
  #   image: postgres
  #   networks:
  #     - openamtnetwork1
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: "postgresadmin"
  #     POSTGRES_PASSWORD: "admin123"
  #     POSTGRES_DB: "rpsdb"
  #   ports:
  #     - 5432:5432
  app:
    build: .
    container_name: app
    image: app
    networks:
      - openamtnetwork1
    env_file:
      - .env
    environment:
      APP_ENCRYPTION_KEY: "Jf3Q2nXJ+GZzN1dbVQms0wbB4+i/5PjL" # This is a test encryption key for the app
      HTTP_HOST: ""
      GIN_MODE: "debug"
      #DB_URL: "postgres://postgresadmin:admin123@postgres:5432/rpsdb"
      APP_AUTH_DISABLED: true
    ports:
      - 8181:8181
      - 4433:4433
    # depends_on:
    #   - postgres
  # integration:
  #   build:
  #     context: .
  #     dockerfile: integration-test/Dockerfile
  #   container_name: integration
  #   image: integration
  #   depends_on:
  #     - app
volumes:
  pg-data:
networks:
  openamtnetwork1:
    driver: "bridge"
