// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/devices/interfaces.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/devices/interfaces.go -package v1 -mock_names Repository=MockDeviceManagementRepository,Feature=MockDeviceManagementFeature
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"
	time "time"

	websocket "github.com/gorilla/websocket"
	entity "github.com/open-amt-cloud-toolkit/console/internal/entity"
	dto "github.com/open-amt-cloud-toolkit/console/internal/entity/dto"
	devices "github.com/open-amt-cloud-toolkit/console/internal/usecase/devices"
	wsman "github.com/open-amt-cloud-toolkit/console/internal/usecase/devices/wsman"
	wsman0 "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman"
	alarmclock "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/alarmclock"
	auditlog "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/auditlog"
	authorization "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/authorization"
	boot "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/boot"
	environmentdetection "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/environmentdetection"
	ethernetport "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/ethernetport"
	general "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/general"
	ieee8021x "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/ieee8021x"
	kerberos "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/kerberos"
	managementpresence "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/managementpresence"
	messagelog "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/messagelog"
	mps "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/mps"
	publickey "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/publickey"
	publicprivate "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/publicprivate"
	redirection "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/redirection"
	remoteaccess "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/remoteaccess"
	setupandconfiguration "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/setupandconfiguration"
	timesynchronization "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/timesynchronization"
	tls "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/tls"
	userinitiatedconnection "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/userinitiatedconnection"
	wifiportconfiguration "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/amt/wifiportconfiguration"
	bios "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/bios"
	boot0 "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/boot"
	card "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/card"
	chassis "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/chassis"
	chip "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/chip"
	computer "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/computer"
	concrete "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/concrete"
	credential "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/credential"
	ieee8021x0 "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/ieee8021x"
	kvm "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/kvm"
	mediaaccess "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/mediaaccess"
	physical "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/physical"
	power "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/power"
	processor "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/processor"
	service "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/service"
	software "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/software"
	system "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/system"
	wifi "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/cim/wifi"
	alarmclock0 "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/ips/alarmclock"
	hostbasedsetup "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/ips/hostbasedsetup"
	ieee8021x1 "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/ips/ieee8021x"
	optin "github.com/open-amt-cloud-toolkit/go-wsman-messages/v2/pkg/wsman/ips/optin"
	gomock "go.uber.org/mock/gomock"
)

// MockAMTExplorer is a mock of AMTExplorer interface.
type MockAMTExplorer struct {
	ctrl     *gomock.Controller
	recorder *MockAMTExplorerMockRecorder
}

// MockAMTExplorerMockRecorder is the mock recorder for MockAMTExplorer.
type MockAMTExplorerMockRecorder struct {
	mock *MockAMTExplorer
}

// NewMockAMTExplorer creates a new mock instance.
func NewMockAMTExplorer(ctrl *gomock.Controller) *MockAMTExplorer {
	mock := &MockAMTExplorer{ctrl: ctrl}
	mock.recorder = &MockAMTExplorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAMTExplorer) EXPECT() *MockAMTExplorerMockRecorder {
	return m.recorder
}

// GetAMT8021xCredentialContext mocks base method.
func (m *MockAMTExplorer) GetAMT8021xCredentialContext() (ieee8021x.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMT8021xCredentialContext")
	ret0, _ := ret[0].(ieee8021x.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMT8021xCredentialContext indicates an expected call of GetAMT8021xCredentialContext.
func (mr *MockAMTExplorerMockRecorder) GetAMT8021xCredentialContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMT8021xCredentialContext", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMT8021xCredentialContext))
}

// GetAMT8021xProfile mocks base method.
func (m *MockAMTExplorer) GetAMT8021xProfile() (ieee8021x.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMT8021xProfile")
	ret0, _ := ret[0].(ieee8021x.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMT8021xProfile indicates an expected call of GetAMT8021xProfile.
func (mr *MockAMTExplorerMockRecorder) GetAMT8021xProfile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMT8021xProfile", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMT8021xProfile))
}

// GetAMTAlarmClockService mocks base method.
func (m *MockAMTExplorer) GetAMTAlarmClockService() (alarmclock.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTAlarmClockService")
	ret0, _ := ret[0].(alarmclock.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTAlarmClockService indicates an expected call of GetAMTAlarmClockService.
func (mr *MockAMTExplorerMockRecorder) GetAMTAlarmClockService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTAlarmClockService", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTAlarmClockService))
}

// GetAMTAuditLog mocks base method.
func (m *MockAMTExplorer) GetAMTAuditLog() (auditlog.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTAuditLog")
	ret0, _ := ret[0].(auditlog.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTAuditLog indicates an expected call of GetAMTAuditLog.
func (mr *MockAMTExplorerMockRecorder) GetAMTAuditLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTAuditLog", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTAuditLog))
}

// GetAMTAuthorizationService mocks base method.
func (m *MockAMTExplorer) GetAMTAuthorizationService() (authorization.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTAuthorizationService")
	ret0, _ := ret[0].(authorization.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTAuthorizationService indicates an expected call of GetAMTAuthorizationService.
func (mr *MockAMTExplorerMockRecorder) GetAMTAuthorizationService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTAuthorizationService", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTAuthorizationService))
}

// GetAMTBootCapabilities mocks base method.
func (m *MockAMTExplorer) GetAMTBootCapabilities() (boot.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTBootCapabilities")
	ret0, _ := ret[0].(boot.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTBootCapabilities indicates an expected call of GetAMTBootCapabilities.
func (mr *MockAMTExplorerMockRecorder) GetAMTBootCapabilities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTBootCapabilities", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTBootCapabilities))
}

// GetAMTBootSettingData mocks base method.
func (m *MockAMTExplorer) GetAMTBootSettingData() (boot.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTBootSettingData")
	ret0, _ := ret[0].(boot.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTBootSettingData indicates an expected call of GetAMTBootSettingData.
func (mr *MockAMTExplorerMockRecorder) GetAMTBootSettingData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTBootSettingData", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTBootSettingData))
}

// GetAMTEnvironmentDetectionSettingData mocks base method.
func (m *MockAMTExplorer) GetAMTEnvironmentDetectionSettingData() (environmentdetection.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTEnvironmentDetectionSettingData")
	ret0, _ := ret[0].(environmentdetection.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTEnvironmentDetectionSettingData indicates an expected call of GetAMTEnvironmentDetectionSettingData.
func (mr *MockAMTExplorerMockRecorder) GetAMTEnvironmentDetectionSettingData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTEnvironmentDetectionSettingData", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTEnvironmentDetectionSettingData))
}

// GetAMTEthernetPortSettings mocks base method.
func (m *MockAMTExplorer) GetAMTEthernetPortSettings() (ethernetport.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTEthernetPortSettings")
	ret0, _ := ret[0].(ethernetport.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTEthernetPortSettings indicates an expected call of GetAMTEthernetPortSettings.
func (mr *MockAMTExplorerMockRecorder) GetAMTEthernetPortSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTEthernetPortSettings", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTEthernetPortSettings))
}

// GetAMTGeneralSettings mocks base method.
func (m *MockAMTExplorer) GetAMTGeneralSettings() (general.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTGeneralSettings")
	ret0, _ := ret[0].(general.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTGeneralSettings indicates an expected call of GetAMTGeneralSettings.
func (mr *MockAMTExplorerMockRecorder) GetAMTGeneralSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTGeneralSettings", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTGeneralSettings))
}

// GetAMTKerberosSettingData mocks base method.
func (m *MockAMTExplorer) GetAMTKerberosSettingData() (kerberos.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTKerberosSettingData")
	ret0, _ := ret[0].(kerberos.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTKerberosSettingData indicates an expected call of GetAMTKerberosSettingData.
func (mr *MockAMTExplorerMockRecorder) GetAMTKerberosSettingData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTKerberosSettingData", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTKerberosSettingData))
}

// GetAMTMPSUsernamePassword mocks base method.
func (m *MockAMTExplorer) GetAMTMPSUsernamePassword() (mps.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTMPSUsernamePassword")
	ret0, _ := ret[0].(mps.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTMPSUsernamePassword indicates an expected call of GetAMTMPSUsernamePassword.
func (mr *MockAMTExplorerMockRecorder) GetAMTMPSUsernamePassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTMPSUsernamePassword", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTMPSUsernamePassword))
}

// GetAMTManagementPresenceRemoteSAP mocks base method.
func (m *MockAMTExplorer) GetAMTManagementPresenceRemoteSAP() (managementpresence.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTManagementPresenceRemoteSAP")
	ret0, _ := ret[0].(managementpresence.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTManagementPresenceRemoteSAP indicates an expected call of GetAMTManagementPresenceRemoteSAP.
func (mr *MockAMTExplorerMockRecorder) GetAMTManagementPresenceRemoteSAP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTManagementPresenceRemoteSAP", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTManagementPresenceRemoteSAP))
}

// GetAMTMessageLog mocks base method.
func (m *MockAMTExplorer) GetAMTMessageLog() (messagelog.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTMessageLog")
	ret0, _ := ret[0].(messagelog.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTMessageLog indicates an expected call of GetAMTMessageLog.
func (mr *MockAMTExplorerMockRecorder) GetAMTMessageLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTMessageLog", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTMessageLog))
}

// GetAMTPublicKeyCertificate mocks base method.
func (m *MockAMTExplorer) GetAMTPublicKeyCertificate() (publickey.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTPublicKeyCertificate")
	ret0, _ := ret[0].(publickey.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTPublicKeyCertificate indicates an expected call of GetAMTPublicKeyCertificate.
func (mr *MockAMTExplorerMockRecorder) GetAMTPublicKeyCertificate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTPublicKeyCertificate", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTPublicKeyCertificate))
}

// GetAMTPublicKeyManagementService mocks base method.
func (m *MockAMTExplorer) GetAMTPublicKeyManagementService() (publickey.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTPublicKeyManagementService")
	ret0, _ := ret[0].(publickey.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTPublicKeyManagementService indicates an expected call of GetAMTPublicKeyManagementService.
func (mr *MockAMTExplorerMockRecorder) GetAMTPublicKeyManagementService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTPublicKeyManagementService", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTPublicKeyManagementService))
}

// GetAMTPublicPrivateKeyPair mocks base method.
func (m *MockAMTExplorer) GetAMTPublicPrivateKeyPair() (publicprivate.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTPublicPrivateKeyPair")
	ret0, _ := ret[0].(publicprivate.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTPublicPrivateKeyPair indicates an expected call of GetAMTPublicPrivateKeyPair.
func (mr *MockAMTExplorerMockRecorder) GetAMTPublicPrivateKeyPair() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTPublicPrivateKeyPair", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTPublicPrivateKeyPair))
}

// GetAMTRedirectionService mocks base method.
func (m *MockAMTExplorer) GetAMTRedirectionService() (redirection.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTRedirectionService")
	ret0, _ := ret[0].(redirection.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTRedirectionService indicates an expected call of GetAMTRedirectionService.
func (mr *MockAMTExplorerMockRecorder) GetAMTRedirectionService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTRedirectionService", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTRedirectionService))
}

// GetAMTRemoteAccessPolicyAppliesToMPS mocks base method.
func (m *MockAMTExplorer) GetAMTRemoteAccessPolicyAppliesToMPS() (remoteaccess.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTRemoteAccessPolicyAppliesToMPS")
	ret0, _ := ret[0].(remoteaccess.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTRemoteAccessPolicyAppliesToMPS indicates an expected call of GetAMTRemoteAccessPolicyAppliesToMPS.
func (mr *MockAMTExplorerMockRecorder) GetAMTRemoteAccessPolicyAppliesToMPS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTRemoteAccessPolicyAppliesToMPS", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTRemoteAccessPolicyAppliesToMPS))
}

// GetAMTRemoteAccessPolicyRule mocks base method.
func (m *MockAMTExplorer) GetAMTRemoteAccessPolicyRule() (remoteaccess.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTRemoteAccessPolicyRule")
	ret0, _ := ret[0].(remoteaccess.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTRemoteAccessPolicyRule indicates an expected call of GetAMTRemoteAccessPolicyRule.
func (mr *MockAMTExplorerMockRecorder) GetAMTRemoteAccessPolicyRule() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTRemoteAccessPolicyRule", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTRemoteAccessPolicyRule))
}

// GetAMTRemoteAccessService mocks base method.
func (m *MockAMTExplorer) GetAMTRemoteAccessService() (remoteaccess.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTRemoteAccessService")
	ret0, _ := ret[0].(remoteaccess.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTRemoteAccessService indicates an expected call of GetAMTRemoteAccessService.
func (mr *MockAMTExplorerMockRecorder) GetAMTRemoteAccessService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTRemoteAccessService", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTRemoteAccessService))
}

// GetAMTSetupAndConfigurationService mocks base method.
func (m *MockAMTExplorer) GetAMTSetupAndConfigurationService() (setupandconfiguration.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTSetupAndConfigurationService")
	ret0, _ := ret[0].(setupandconfiguration.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTSetupAndConfigurationService indicates an expected call of GetAMTSetupAndConfigurationService.
func (mr *MockAMTExplorerMockRecorder) GetAMTSetupAndConfigurationService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTSetupAndConfigurationService", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTSetupAndConfigurationService))
}

// GetAMTTLSCredentialContext mocks base method.
func (m *MockAMTExplorer) GetAMTTLSCredentialContext() (tls.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTTLSCredentialContext")
	ret0, _ := ret[0].(tls.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTTLSCredentialContext indicates an expected call of GetAMTTLSCredentialContext.
func (mr *MockAMTExplorerMockRecorder) GetAMTTLSCredentialContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTTLSCredentialContext", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTTLSCredentialContext))
}

// GetAMTTLSProtocolEndpointCollection mocks base method.
func (m *MockAMTExplorer) GetAMTTLSProtocolEndpointCollection() (tls.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTTLSProtocolEndpointCollection")
	ret0, _ := ret[0].(tls.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTTLSProtocolEndpointCollection indicates an expected call of GetAMTTLSProtocolEndpointCollection.
func (mr *MockAMTExplorerMockRecorder) GetAMTTLSProtocolEndpointCollection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTTLSProtocolEndpointCollection", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTTLSProtocolEndpointCollection))
}

// GetAMTTLSSettingData mocks base method.
func (m *MockAMTExplorer) GetAMTTLSSettingData() (tls.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTTLSSettingData")
	ret0, _ := ret[0].(tls.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTTLSSettingData indicates an expected call of GetAMTTLSSettingData.
func (mr *MockAMTExplorerMockRecorder) GetAMTTLSSettingData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTTLSSettingData", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTTLSSettingData))
}

// GetAMTTimeSynchronizationService mocks base method.
func (m *MockAMTExplorer) GetAMTTimeSynchronizationService() (timesynchronization.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTTimeSynchronizationService")
	ret0, _ := ret[0].(timesynchronization.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTTimeSynchronizationService indicates an expected call of GetAMTTimeSynchronizationService.
func (mr *MockAMTExplorerMockRecorder) GetAMTTimeSynchronizationService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTTimeSynchronizationService", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTTimeSynchronizationService))
}

// GetAMTUserInitiatedConnectionService mocks base method.
func (m *MockAMTExplorer) GetAMTUserInitiatedConnectionService() (userinitiatedconnection.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTUserInitiatedConnectionService")
	ret0, _ := ret[0].(userinitiatedconnection.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTUserInitiatedConnectionService indicates an expected call of GetAMTUserInitiatedConnectionService.
func (mr *MockAMTExplorerMockRecorder) GetAMTUserInitiatedConnectionService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTUserInitiatedConnectionService", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTUserInitiatedConnectionService))
}

// GetAMTWiFiPortConifgurationService mocks base method.
func (m *MockAMTExplorer) GetAMTWiFiPortConifgurationService() (wifiportconfiguration.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTWiFiPortConifgurationService")
	ret0, _ := ret[0].(wifiportconfiguration.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTWiFiPortConifgurationService indicates an expected call of GetAMTWiFiPortConifgurationService.
func (mr *MockAMTExplorerMockRecorder) GetAMTWiFiPortConifgurationService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTWiFiPortConifgurationService", reflect.TypeOf((*MockAMTExplorer)(nil).GetAMTWiFiPortConifgurationService))
}

// GetCIMBIOSElement mocks base method.
func (m *MockAMTExplorer) GetCIMBIOSElement() (bios.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMBIOSElement")
	ret0, _ := ret[0].(bios.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMBIOSElement indicates an expected call of GetCIMBIOSElement.
func (mr *MockAMTExplorerMockRecorder) GetCIMBIOSElement() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMBIOSElement", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMBIOSElement))
}

// GetCIMBootConfigSetting mocks base method.
func (m *MockAMTExplorer) GetCIMBootConfigSetting() (boot0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMBootConfigSetting")
	ret0, _ := ret[0].(boot0.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMBootConfigSetting indicates an expected call of GetCIMBootConfigSetting.
func (mr *MockAMTExplorerMockRecorder) GetCIMBootConfigSetting() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMBootConfigSetting", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMBootConfigSetting))
}

// GetCIMBootService mocks base method.
func (m *MockAMTExplorer) GetCIMBootService() (boot0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMBootService")
	ret0, _ := ret[0].(boot0.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMBootService indicates an expected call of GetCIMBootService.
func (mr *MockAMTExplorerMockRecorder) GetCIMBootService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMBootService", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMBootService))
}

// GetCIMBootSourceSetting mocks base method.
func (m *MockAMTExplorer) GetCIMBootSourceSetting() (boot0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMBootSourceSetting")
	ret0, _ := ret[0].(boot0.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMBootSourceSetting indicates an expected call of GetCIMBootSourceSetting.
func (mr *MockAMTExplorerMockRecorder) GetCIMBootSourceSetting() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMBootSourceSetting", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMBootSourceSetting))
}

// GetCIMCard mocks base method.
func (m *MockAMTExplorer) GetCIMCard() (card.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMCard")
	ret0, _ := ret[0].(card.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMCard indicates an expected call of GetCIMCard.
func (mr *MockAMTExplorerMockRecorder) GetCIMCard() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMCard", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMCard))
}

// GetCIMChassis mocks base method.
func (m *MockAMTExplorer) GetCIMChassis() (chassis.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMChassis")
	ret0, _ := ret[0].(chassis.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMChassis indicates an expected call of GetCIMChassis.
func (mr *MockAMTExplorerMockRecorder) GetCIMChassis() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMChassis", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMChassis))
}

// GetCIMChip mocks base method.
func (m *MockAMTExplorer) GetCIMChip() (chip.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMChip")
	ret0, _ := ret[0].(chip.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMChip indicates an expected call of GetCIMChip.
func (mr *MockAMTExplorerMockRecorder) GetCIMChip() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMChip", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMChip))
}

// GetCIMComputerSystemPackage mocks base method.
func (m *MockAMTExplorer) GetCIMComputerSystemPackage() (computer.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMComputerSystemPackage")
	ret0, _ := ret[0].(computer.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMComputerSystemPackage indicates an expected call of GetCIMComputerSystemPackage.
func (mr *MockAMTExplorerMockRecorder) GetCIMComputerSystemPackage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMComputerSystemPackage", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMComputerSystemPackage))
}

// GetCIMConcreteDependency mocks base method.
func (m *MockAMTExplorer) GetCIMConcreteDependency() (concrete.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMConcreteDependency")
	ret0, _ := ret[0].(concrete.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMConcreteDependency indicates an expected call of GetCIMConcreteDependency.
func (mr *MockAMTExplorerMockRecorder) GetCIMConcreteDependency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMConcreteDependency", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMConcreteDependency))
}

// GetCIMCredentialContext mocks base method.
func (m *MockAMTExplorer) GetCIMCredentialContext() (credential.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMCredentialContext")
	ret0, _ := ret[0].(credential.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMCredentialContext indicates an expected call of GetCIMCredentialContext.
func (mr *MockAMTExplorerMockRecorder) GetCIMCredentialContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMCredentialContext", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMCredentialContext))
}

// GetCIMIEEE8021xSettings mocks base method.
func (m *MockAMTExplorer) GetCIMIEEE8021xSettings() (ieee8021x0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMIEEE8021xSettings")
	ret0, _ := ret[0].(ieee8021x0.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMIEEE8021xSettings indicates an expected call of GetCIMIEEE8021xSettings.
func (mr *MockAMTExplorerMockRecorder) GetCIMIEEE8021xSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMIEEE8021xSettings", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMIEEE8021xSettings))
}

// GetCIMKVMRedirectionSAP mocks base method.
func (m *MockAMTExplorer) GetCIMKVMRedirectionSAP() (kvm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMKVMRedirectionSAP")
	ret0, _ := ret[0].(kvm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMKVMRedirectionSAP indicates an expected call of GetCIMKVMRedirectionSAP.
func (mr *MockAMTExplorerMockRecorder) GetCIMKVMRedirectionSAP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMKVMRedirectionSAP", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMKVMRedirectionSAP))
}

// GetCIMMediaAccessDevice mocks base method.
func (m *MockAMTExplorer) GetCIMMediaAccessDevice() (mediaaccess.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMMediaAccessDevice")
	ret0, _ := ret[0].(mediaaccess.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMMediaAccessDevice indicates an expected call of GetCIMMediaAccessDevice.
func (mr *MockAMTExplorerMockRecorder) GetCIMMediaAccessDevice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMMediaAccessDevice", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMMediaAccessDevice))
}

// GetCIMPhysicalMemory mocks base method.
func (m *MockAMTExplorer) GetCIMPhysicalMemory() (physical.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMPhysicalMemory")
	ret0, _ := ret[0].(physical.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMPhysicalMemory indicates an expected call of GetCIMPhysicalMemory.
func (mr *MockAMTExplorerMockRecorder) GetCIMPhysicalMemory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMPhysicalMemory", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMPhysicalMemory))
}

// GetCIMPhysicalPackage mocks base method.
func (m *MockAMTExplorer) GetCIMPhysicalPackage() (physical.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMPhysicalPackage")
	ret0, _ := ret[0].(physical.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMPhysicalPackage indicates an expected call of GetCIMPhysicalPackage.
func (mr *MockAMTExplorerMockRecorder) GetCIMPhysicalPackage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMPhysicalPackage", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMPhysicalPackage))
}

// GetCIMPowerManagementService mocks base method.
func (m *MockAMTExplorer) GetCIMPowerManagementService() (power.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMPowerManagementService")
	ret0, _ := ret[0].(power.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMPowerManagementService indicates an expected call of GetCIMPowerManagementService.
func (mr *MockAMTExplorerMockRecorder) GetCIMPowerManagementService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMPowerManagementService", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMPowerManagementService))
}

// GetCIMProcessor mocks base method.
func (m *MockAMTExplorer) GetCIMProcessor() (processor.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMProcessor")
	ret0, _ := ret[0].(processor.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMProcessor indicates an expected call of GetCIMProcessor.
func (mr *MockAMTExplorerMockRecorder) GetCIMProcessor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMProcessor", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMProcessor))
}

// GetCIMServiceAvailableToElement mocks base method.
func (m *MockAMTExplorer) GetCIMServiceAvailableToElement() (service.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMServiceAvailableToElement")
	ret0, _ := ret[0].(service.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMServiceAvailableToElement indicates an expected call of GetCIMServiceAvailableToElement.
func (mr *MockAMTExplorerMockRecorder) GetCIMServiceAvailableToElement() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMServiceAvailableToElement", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMServiceAvailableToElement))
}

// GetCIMSoftwareIdentity mocks base method.
func (m *MockAMTExplorer) GetCIMSoftwareIdentity() (software.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMSoftwareIdentity")
	ret0, _ := ret[0].(software.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMSoftwareIdentity indicates an expected call of GetCIMSoftwareIdentity.
func (mr *MockAMTExplorerMockRecorder) GetCIMSoftwareIdentity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMSoftwareIdentity", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMSoftwareIdentity))
}

// GetCIMSystemPackaging mocks base method.
func (m *MockAMTExplorer) GetCIMSystemPackaging() (system.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMSystemPackaging")
	ret0, _ := ret[0].(system.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMSystemPackaging indicates an expected call of GetCIMSystemPackaging.
func (mr *MockAMTExplorerMockRecorder) GetCIMSystemPackaging() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMSystemPackaging", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMSystemPackaging))
}

// GetCIMWiFiEndpointSettings mocks base method.
func (m *MockAMTExplorer) GetCIMWiFiEndpointSettings() (wifi.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMWiFiEndpointSettings")
	ret0, _ := ret[0].(wifi.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMWiFiEndpointSettings indicates an expected call of GetCIMWiFiEndpointSettings.
func (mr *MockAMTExplorerMockRecorder) GetCIMWiFiEndpointSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMWiFiEndpointSettings", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMWiFiEndpointSettings))
}

// GetCIMWiFiPort mocks base method.
func (m *MockAMTExplorer) GetCIMWiFiPort() (wifi.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCIMWiFiPort")
	ret0, _ := ret[0].(wifi.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCIMWiFiPort indicates an expected call of GetCIMWiFiPort.
func (mr *MockAMTExplorerMockRecorder) GetCIMWiFiPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCIMWiFiPort", reflect.TypeOf((*MockAMTExplorer)(nil).GetCIMWiFiPort))
}

// GetIPS8021xCredentialContext mocks base method.
func (m *MockAMTExplorer) GetIPS8021xCredentialContext() (ieee8021x1.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPS8021xCredentialContext")
	ret0, _ := ret[0].(ieee8021x1.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPS8021xCredentialContext indicates an expected call of GetIPS8021xCredentialContext.
func (mr *MockAMTExplorerMockRecorder) GetIPS8021xCredentialContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPS8021xCredentialContext", reflect.TypeOf((*MockAMTExplorer)(nil).GetIPS8021xCredentialContext))
}

// GetIPSAlarmClockOccurrence mocks base method.
func (m *MockAMTExplorer) GetIPSAlarmClockOccurrence() (alarmclock0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPSAlarmClockOccurrence")
	ret0, _ := ret[0].(alarmclock0.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPSAlarmClockOccurrence indicates an expected call of GetIPSAlarmClockOccurrence.
func (mr *MockAMTExplorerMockRecorder) GetIPSAlarmClockOccurrence() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPSAlarmClockOccurrence", reflect.TypeOf((*MockAMTExplorer)(nil).GetIPSAlarmClockOccurrence))
}

// GetIPSHostBasedSetupService mocks base method.
func (m *MockAMTExplorer) GetIPSHostBasedSetupService() (hostbasedsetup.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPSHostBasedSetupService")
	ret0, _ := ret[0].(hostbasedsetup.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPSHostBasedSetupService indicates an expected call of GetIPSHostBasedSetupService.
func (mr *MockAMTExplorerMockRecorder) GetIPSHostBasedSetupService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPSHostBasedSetupService", reflect.TypeOf((*MockAMTExplorer)(nil).GetIPSHostBasedSetupService))
}

// GetIPSIEEE8021xSettings mocks base method.
func (m *MockAMTExplorer) GetIPSIEEE8021xSettings() (ieee8021x1.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPSIEEE8021xSettings")
	ret0, _ := ret[0].(ieee8021x1.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPSIEEE8021xSettings indicates an expected call of GetIPSIEEE8021xSettings.
func (mr *MockAMTExplorerMockRecorder) GetIPSIEEE8021xSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPSIEEE8021xSettings", reflect.TypeOf((*MockAMTExplorer)(nil).GetIPSIEEE8021xSettings))
}

// GetIPSOptInService mocks base method.
func (m *MockAMTExplorer) GetIPSOptInService() (optin.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPSOptInService")
	ret0, _ := ret[0].(optin.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPSOptInService indicates an expected call of GetIPSOptInService.
func (mr *MockAMTExplorerMockRecorder) GetIPSOptInService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPSOptInService", reflect.TypeOf((*MockAMTExplorer)(nil).GetIPSOptInService))
}

// SetupWsmanClient mocks base method.
func (m *MockAMTExplorer) SetupWsmanClient(device dto.Device, isRedirection, logAMTMessages bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupWsmanClient", device, isRedirection, logAMTMessages)
}

// SetupWsmanClient indicates an expected call of SetupWsmanClient.
func (mr *MockAMTExplorerMockRecorder) SetupWsmanClient(device, isRedirection, logAMTMessages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupWsmanClient", reflect.TypeOf((*MockAMTExplorer)(nil).SetupWsmanClient), device, isRedirection, logAMTMessages)
}

// MockManagement is a mock of Management interface.
type MockManagement struct {
	ctrl     *gomock.Controller
	recorder *MockManagementMockRecorder
}

// MockManagementMockRecorder is the mock recorder for MockManagement.
type MockManagementMockRecorder struct {
	mock *MockManagement
}

// NewMockManagement creates a new mock instance.
func NewMockManagement(ctrl *gomock.Controller) *MockManagement {
	mock := &MockManagement{ctrl: ctrl}
	mock.recorder = &MockManagementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagement) EXPECT() *MockManagementMockRecorder {
	return m.recorder
}

// CancelUserConsentRequest mocks base method.
func (m *MockManagement) CancelUserConsentRequest() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelUserConsentRequest")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelUserConsentRequest indicates an expected call of CancelUserConsentRequest.
func (mr *MockManagementMockRecorder) CancelUserConsentRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelUserConsentRequest", reflect.TypeOf((*MockManagement)(nil).CancelUserConsentRequest))
}

// ChangeBootOrder mocks base method.
func (m *MockManagement) ChangeBootOrder(bootSource string) (boot0.ChangeBootOrder_OUTPUT, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeBootOrder", bootSource)
	ret0, _ := ret[0].(boot0.ChangeBootOrder_OUTPUT)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeBootOrder indicates an expected call of ChangeBootOrder.
func (mr *MockManagementMockRecorder) ChangeBootOrder(bootSource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeBootOrder", reflect.TypeOf((*MockManagement)(nil).ChangeBootOrder), bootSource)
}

// CreateAlarmOccurrences mocks base method.
func (m *MockManagement) CreateAlarmOccurrences(name string, startTime time.Time, interval int, deleteOnCompletion bool) (alarmclock.AddAlarmOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlarmOccurrences", name, startTime, interval, deleteOnCompletion)
	ret0, _ := ret[0].(alarmclock.AddAlarmOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlarmOccurrences indicates an expected call of CreateAlarmOccurrences.
func (mr *MockManagementMockRecorder) CreateAlarmOccurrences(name, startTime, interval, deleteOnCompletion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlarmOccurrences", reflect.TypeOf((*MockManagement)(nil).CreateAlarmOccurrences), name, startTime, interval, deleteOnCompletion)
}

// DeleteAlarmOccurrences mocks base method.
func (m *MockManagement) DeleteAlarmOccurrences(instanceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlarmOccurrences", instanceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlarmOccurrences indicates an expected call of DeleteAlarmOccurrences.
func (mr *MockManagementMockRecorder) DeleteAlarmOccurrences(instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlarmOccurrences", reflect.TypeOf((*MockManagement)(nil).DeleteAlarmOccurrences), instanceID)
}

// DestroyWsmanClient mocks base method.
func (m *MockManagement) DestroyWsmanClient(device dto.Device) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DestroyWsmanClient", device)
}

// DestroyWsmanClient indicates an expected call of DestroyWsmanClient.
func (mr *MockManagementMockRecorder) DestroyWsmanClient(device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyWsmanClient", reflect.TypeOf((*MockManagement)(nil).DestroyWsmanClient), device)
}

// GetAMTVersion mocks base method.
func (m *MockManagement) GetAMTVersion() ([]software.SoftwareIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAMTVersion")
	ret0, _ := ret[0].([]software.SoftwareIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAMTVersion indicates an expected call of GetAMTVersion.
func (mr *MockManagementMockRecorder) GetAMTVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAMTVersion", reflect.TypeOf((*MockManagement)(nil).GetAMTVersion))
}

// GetAlarmOccurrences mocks base method.
func (m *MockManagement) GetAlarmOccurrences() ([]alarmclock0.AlarmClockOccurrence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlarmOccurrences")
	ret0, _ := ret[0].([]alarmclock0.AlarmClockOccurrence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlarmOccurrences indicates an expected call of GetAlarmOccurrences.
func (mr *MockManagementMockRecorder) GetAlarmOccurrences() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlarmOccurrences", reflect.TypeOf((*MockManagement)(nil).GetAlarmOccurrences))
}

// GetAuditLog mocks base method.
func (m *MockManagement) GetAuditLog(startIndex int) (auditlog.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditLog", startIndex)
	ret0, _ := ret[0].(auditlog.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditLog indicates an expected call of GetAuditLog.
func (mr *MockManagementMockRecorder) GetAuditLog(startIndex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditLog", reflect.TypeOf((*MockManagement)(nil).GetAuditLog), startIndex)
}

// GetBootData mocks base method.
func (m *MockManagement) GetBootData() (boot.BootCapabilitiesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBootData")
	ret0, _ := ret[0].(boot.BootCapabilitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBootData indicates an expected call of GetBootData.
func (mr *MockManagementMockRecorder) GetBootData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBootData", reflect.TypeOf((*MockManagement)(nil).GetBootData))
}

// GetCertificates mocks base method.
func (m *MockManagement) GetCertificates() (wsman.Certificates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificates")
	ret0, _ := ret[0].(wsman.Certificates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCertificates indicates an expected call of GetCertificates.
func (mr *MockManagementMockRecorder) GetCertificates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificates", reflect.TypeOf((*MockManagement)(nil).GetCertificates))
}

// GetConcreteDependencies mocks base method.
func (m *MockManagement) GetConcreteDependencies() ([]concrete.ConcreteDependency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConcreteDependencies")
	ret0, _ := ret[0].([]concrete.ConcreteDependency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConcreteDependencies indicates an expected call of GetConcreteDependencies.
func (mr *MockManagementMockRecorder) GetConcreteDependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConcreteDependencies", reflect.TypeOf((*MockManagement)(nil).GetConcreteDependencies))
}

// GetCredentialRelationships mocks base method.
func (m *MockManagement) GetCredentialRelationships() (credential.Items, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialRelationships")
	ret0, _ := ret[0].(credential.Items)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialRelationships indicates an expected call of GetCredentialRelationships.
func (mr *MockManagementMockRecorder) GetCredentialRelationships() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialRelationships", reflect.TypeOf((*MockManagement)(nil).GetCredentialRelationships))
}

// GetEventLog mocks base method.
func (m *MockManagement) GetEventLog() (messagelog.GetRecordsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventLog")
	ret0, _ := ret[0].(messagelog.GetRecordsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventLog indicates an expected call of GetEventLog.
func (mr *MockManagementMockRecorder) GetEventLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventLog", reflect.TypeOf((*MockManagement)(nil).GetEventLog))
}

// GetFeatures mocks base method.
func (m *MockManagement) GetFeatures() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatures")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatures indicates an expected call of GetFeatures.
func (mr *MockManagementMockRecorder) GetFeatures() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatures", reflect.TypeOf((*MockManagement)(nil).GetFeatures))
}

// GetGeneralSettings mocks base method.
func (m *MockManagement) GetGeneralSettings() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralSettings")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralSettings indicates an expected call of GetGeneralSettings.
func (mr *MockManagementMockRecorder) GetGeneralSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralSettings", reflect.TypeOf((*MockManagement)(nil).GetGeneralSettings))
}

// GetHardwareInfo mocks base method.
func (m *MockManagement) GetHardwareInfo() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHardwareInfo")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHardwareInfo indicates an expected call of GetHardwareInfo.
func (mr *MockManagementMockRecorder) GetHardwareInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHardwareInfo", reflect.TypeOf((*MockManagement)(nil).GetHardwareInfo))
}

// GetNetworkSettings mocks base method.
func (m *MockManagement) GetNetworkSettings() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkSettings")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkSettings indicates an expected call of GetNetworkSettings.
func (mr *MockManagementMockRecorder) GetNetworkSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkSettings", reflect.TypeOf((*MockManagement)(nil).GetNetworkSettings))
}

// GetPowerCapabilities mocks base method.
func (m *MockManagement) GetPowerCapabilities() (boot.BootCapabilitiesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerCapabilities")
	ret0, _ := ret[0].(boot.BootCapabilitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPowerCapabilities indicates an expected call of GetPowerCapabilities.
func (mr *MockManagementMockRecorder) GetPowerCapabilities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerCapabilities", reflect.TypeOf((*MockManagement)(nil).GetPowerCapabilities))
}

// GetPowerState mocks base method.
func (m *MockManagement) GetPowerState() ([]service.CIM_AssociatedPowerManagementService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerState")
	ret0, _ := ret[0].([]service.CIM_AssociatedPowerManagementService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPowerState indicates an expected call of GetPowerState.
func (mr *MockManagementMockRecorder) GetPowerState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerState", reflect.TypeOf((*MockManagement)(nil).GetPowerState))
}

// GetSetupAndConfiguration mocks base method.
func (m *MockManagement) GetSetupAndConfiguration() ([]setupandconfiguration.SetupAndConfigurationServiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetupAndConfiguration")
	ret0, _ := ret[0].([]setupandconfiguration.SetupAndConfigurationServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetupAndConfiguration indicates an expected call of GetSetupAndConfiguration.
func (mr *MockManagementMockRecorder) GetSetupAndConfiguration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetupAndConfiguration", reflect.TypeOf((*MockManagement)(nil).GetSetupAndConfiguration))
}

// GetUserConsentCode mocks base method.
func (m *MockManagement) GetUserConsentCode() (optin.StartOptIn_OUTPUT, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserConsentCode")
	ret0, _ := ret[0].(optin.StartOptIn_OUTPUT)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserConsentCode indicates an expected call of GetUserConsentCode.
func (mr *MockManagementMockRecorder) GetUserConsentCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserConsentCode", reflect.TypeOf((*MockManagement)(nil).GetUserConsentCode))
}

// SendConsentCode mocks base method.
func (m *MockManagement) SendConsentCode(code int) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConsentCode", code)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendConsentCode indicates an expected call of SendConsentCode.
func (mr *MockManagementMockRecorder) SendConsentCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConsentCode", reflect.TypeOf((*MockManagement)(nil).SendConsentCode), code)
}

// SendPowerAction mocks base method.
func (m *MockManagement) SendPowerAction(action int) (power.PowerActionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPowerAction", action)
	ret0, _ := ret[0].(power.PowerActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPowerAction indicates an expected call of SendPowerAction.
func (mr *MockManagementMockRecorder) SendPowerAction(action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPowerAction", reflect.TypeOf((*MockManagement)(nil).SendPowerAction), action)
}

// SetBootConfigRole mocks base method.
func (m *MockManagement) SetBootConfigRole(role int) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBootConfigRole", role)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBootConfigRole indicates an expected call of SetBootConfigRole.
func (mr *MockManagementMockRecorder) SetBootConfigRole(role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBootConfigRole", reflect.TypeOf((*MockManagement)(nil).SetBootConfigRole), role)
}

// SetBootData mocks base method.
func (m *MockManagement) SetBootData(data boot.BootSettingDataRequest) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBootData", data)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBootData indicates an expected call of SetBootData.
func (mr *MockManagementMockRecorder) SetBootData(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBootData", reflect.TypeOf((*MockManagement)(nil).SetBootData), data)
}

// SetFeatures mocks base method.
func (m *MockManagement) SetFeatures(arg0 dto.Features) (dto.Features, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFeatures", arg0)
	ret0, _ := ret[0].(dto.Features)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetFeatures indicates an expected call of SetFeatures.
func (mr *MockManagementMockRecorder) SetFeatures(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFeatures", reflect.TypeOf((*MockManagement)(nil).SetFeatures), arg0)
}

// SetupWsmanClient mocks base method.
func (m *MockManagement) SetupWsmanClient(device dto.Device, isRedirection, logMessages bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupWsmanClient", device, isRedirection, logMessages)
}

// SetupWsmanClient indicates an expected call of SetupWsmanClient.
func (mr *MockManagementMockRecorder) SetupWsmanClient(device, isRedirection, logMessages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupWsmanClient", reflect.TypeOf((*MockManagement)(nil).SetupWsmanClient), device, isRedirection, logMessages)
}

// MockRedirection is a mock of Redirection interface.
type MockRedirection struct {
	ctrl     *gomock.Controller
	recorder *MockRedirectionMockRecorder
}

// MockRedirectionMockRecorder is the mock recorder for MockRedirection.
type MockRedirectionMockRecorder struct {
	mock *MockRedirection
}

// NewMockRedirection creates a new mock instance.
func NewMockRedirection(ctrl *gomock.Controller) *MockRedirection {
	mock := &MockRedirection{ctrl: ctrl}
	mock.recorder = &MockRedirectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedirection) EXPECT() *MockRedirectionMockRecorder {
	return m.recorder
}

// RedirectClose mocks base method.
func (m *MockRedirection) RedirectClose(ctx context.Context, deviceConnection *devices.DeviceConnection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedirectClose", ctx, deviceConnection)
	ret0, _ := ret[0].(error)
	return ret0
}

// RedirectClose indicates an expected call of RedirectClose.
func (mr *MockRedirectionMockRecorder) RedirectClose(ctx, deviceConnection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectClose", reflect.TypeOf((*MockRedirection)(nil).RedirectClose), ctx, deviceConnection)
}

// RedirectConnect mocks base method.
func (m *MockRedirection) RedirectConnect(ctx context.Context, deviceConnection *devices.DeviceConnection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedirectConnect", ctx, deviceConnection)
	ret0, _ := ret[0].(error)
	return ret0
}

// RedirectConnect indicates an expected call of RedirectConnect.
func (mr *MockRedirectionMockRecorder) RedirectConnect(ctx, deviceConnection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectConnect", reflect.TypeOf((*MockRedirection)(nil).RedirectConnect), ctx, deviceConnection)
}

// RedirectListen mocks base method.
func (m *MockRedirection) RedirectListen(ctx context.Context, deviceConnection *devices.DeviceConnection) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedirectListen", ctx, deviceConnection)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RedirectListen indicates an expected call of RedirectListen.
func (mr *MockRedirectionMockRecorder) RedirectListen(ctx, deviceConnection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectListen", reflect.TypeOf((*MockRedirection)(nil).RedirectListen), ctx, deviceConnection)
}

// RedirectSend mocks base method.
func (m *MockRedirection) RedirectSend(ctx context.Context, deviceConnection *devices.DeviceConnection, message []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedirectSend", ctx, deviceConnection, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// RedirectSend indicates an expected call of RedirectSend.
func (mr *MockRedirectionMockRecorder) RedirectSend(ctx, deviceConnection, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectSend", reflect.TypeOf((*MockRedirection)(nil).RedirectSend), ctx, deviceConnection, message)
}

// SetupWsmanClient mocks base method.
func (m *MockRedirection) SetupWsmanClient(device dto.Device, isRedirection, logMessages bool) wsman0.Messages {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupWsmanClient", device, isRedirection, logMessages)
	ret0, _ := ret[0].(wsman0.Messages)
	return ret0
}

// SetupWsmanClient indicates an expected call of SetupWsmanClient.
func (mr *MockRedirectionMockRecorder) SetupWsmanClient(device, isRedirection, logMessages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupWsmanClient", reflect.TypeOf((*MockRedirection)(nil).SetupWsmanClient), device, isRedirection, logMessages)
}

// MockDeviceManagementRepository is a mock of Repository interface.
type MockDeviceManagementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceManagementRepositoryMockRecorder
}

// MockDeviceManagementRepositoryMockRecorder is the mock recorder for MockDeviceManagementRepository.
type MockDeviceManagementRepositoryMockRecorder struct {
	mock *MockDeviceManagementRepository
}

// NewMockDeviceManagementRepository creates a new mock instance.
func NewMockDeviceManagementRepository(ctrl *gomock.Controller) *MockDeviceManagementRepository {
	mock := &MockDeviceManagementRepository{ctrl: ctrl}
	mock.recorder = &MockDeviceManagementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceManagementRepository) EXPECT() *MockDeviceManagementRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeviceManagementRepository) Delete(ctx context.Context, guid, tenantID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, guid, tenantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceManagementRepositoryMockRecorder) Delete(ctx, guid, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceManagementRepository)(nil).Delete), ctx, guid, tenantID)
}

// Get mocks base method.
func (m *MockDeviceManagementRepository) Get(ctx context.Context, top, skip int, tenantID string) ([]entity.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, top, skip, tenantID)
	ret0, _ := ret[0].([]entity.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDeviceManagementRepositoryMockRecorder) Get(ctx, top, skip, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeviceManagementRepository)(nil).Get), ctx, top, skip, tenantID)
}

// GetByColumn mocks base method.
func (m *MockDeviceManagementRepository) GetByColumn(ctx context.Context, columnName, queryValue, tenantId string) ([]entity.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByColumn", ctx, columnName, queryValue, tenantId)
	ret0, _ := ret[0].([]entity.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByColumn indicates an expected call of GetByColumn.
func (mr *MockDeviceManagementRepositoryMockRecorder) GetByColumn(ctx, columnName, queryValue, tenantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByColumn", reflect.TypeOf((*MockDeviceManagementRepository)(nil).GetByColumn), ctx, columnName, queryValue, tenantId)
}

// GetByID mocks base method.
func (m *MockDeviceManagementRepository) GetByID(ctx context.Context, guid, tenantID string) (*entity.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, guid, tenantID)
	ret0, _ := ret[0].(*entity.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeviceManagementRepositoryMockRecorder) GetByID(ctx, guid, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeviceManagementRepository)(nil).GetByID), ctx, guid, tenantID)
}

// GetByTags mocks base method.
func (m *MockDeviceManagementRepository) GetByTags(ctx context.Context, tags []string, method string, limit, offset int, tenantID string) ([]entity.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTags", ctx, tags, method, limit, offset, tenantID)
	ret0, _ := ret[0].([]entity.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTags indicates an expected call of GetByTags.
func (mr *MockDeviceManagementRepositoryMockRecorder) GetByTags(ctx, tags, method, limit, offset, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTags", reflect.TypeOf((*MockDeviceManagementRepository)(nil).GetByTags), ctx, tags, method, limit, offset, tenantID)
}

// GetCount mocks base method.
func (m *MockDeviceManagementRepository) GetCount(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCount", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCount indicates an expected call of GetCount.
func (mr *MockDeviceManagementRepositoryMockRecorder) GetCount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockDeviceManagementRepository)(nil).GetCount), arg0, arg1)
}

// GetDistinctTags mocks base method.
func (m *MockDeviceManagementRepository) GetDistinctTags(ctx context.Context, tenantID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctTags", ctx, tenantID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctTags indicates an expected call of GetDistinctTags.
func (mr *MockDeviceManagementRepositoryMockRecorder) GetDistinctTags(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctTags", reflect.TypeOf((*MockDeviceManagementRepository)(nil).GetDistinctTags), ctx, tenantID)
}

// Insert mocks base method.
func (m *MockDeviceManagementRepository) Insert(ctx context.Context, d *entity.Device) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, d)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockDeviceManagementRepositoryMockRecorder) Insert(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDeviceManagementRepository)(nil).Insert), ctx, d)
}

// Update mocks base method.
func (m *MockDeviceManagementRepository) Update(ctx context.Context, d *entity.Device) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, d)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDeviceManagementRepositoryMockRecorder) Update(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceManagementRepository)(nil).Update), ctx, d)
}

// MockDeviceManagementFeature is a mock of Feature interface.
type MockDeviceManagementFeature struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceManagementFeatureMockRecorder
}

// MockDeviceManagementFeatureMockRecorder is the mock recorder for MockDeviceManagementFeature.
type MockDeviceManagementFeatureMockRecorder struct {
	mock *MockDeviceManagementFeature
}

// NewMockDeviceManagementFeature creates a new mock instance.
func NewMockDeviceManagementFeature(ctrl *gomock.Controller) *MockDeviceManagementFeature {
	mock := &MockDeviceManagementFeature{ctrl: ctrl}
	mock.recorder = &MockDeviceManagementFeatureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceManagementFeature) EXPECT() *MockDeviceManagementFeatureMockRecorder {
	return m.recorder
}

// CancelUserConsent mocks base method.
func (m *MockDeviceManagementFeature) CancelUserConsent(ctx context.Context, guid string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelUserConsent", ctx, guid)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelUserConsent indicates an expected call of CancelUserConsent.
func (mr *MockDeviceManagementFeatureMockRecorder) CancelUserConsent(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelUserConsent", reflect.TypeOf((*MockDeviceManagementFeature)(nil).CancelUserConsent), ctx, guid)
}

// CreateAlarmOccurrences mocks base method.
func (m *MockDeviceManagementFeature) CreateAlarmOccurrences(ctx context.Context, guid string, alarm dto.AlarmClockOccurrence) (dto.AddAlarmOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlarmOccurrences", ctx, guid, alarm)
	ret0, _ := ret[0].(dto.AddAlarmOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAlarmOccurrences indicates an expected call of CreateAlarmOccurrences.
func (mr *MockDeviceManagementFeatureMockRecorder) CreateAlarmOccurrences(ctx, guid, alarm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlarmOccurrences", reflect.TypeOf((*MockDeviceManagementFeature)(nil).CreateAlarmOccurrences), ctx, guid, alarm)
}

// Delete mocks base method.
func (m *MockDeviceManagementFeature) Delete(ctx context.Context, guid, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, guid, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceManagementFeatureMockRecorder) Delete(ctx, guid, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceManagementFeature)(nil).Delete), ctx, guid, tenantID)
}

// DeleteAlarmOccurrences mocks base method.
func (m *MockDeviceManagementFeature) DeleteAlarmOccurrences(ctx context.Context, guid, instanceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAlarmOccurrences", ctx, guid, instanceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAlarmOccurrences indicates an expected call of DeleteAlarmOccurrences.
func (mr *MockDeviceManagementFeatureMockRecorder) DeleteAlarmOccurrences(ctx, guid, instanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAlarmOccurrences", reflect.TypeOf((*MockDeviceManagementFeature)(nil).DeleteAlarmOccurrences), ctx, guid, instanceID)
}

// ExecuteCall mocks base method.
func (m *MockDeviceManagementFeature) ExecuteCall(ctx context.Context, guid, call, tenantID string) (*dto.Explorer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCall", ctx, guid, call, tenantID)
	ret0, _ := ret[0].(*dto.Explorer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteCall indicates an expected call of ExecuteCall.
func (mr *MockDeviceManagementFeatureMockRecorder) ExecuteCall(ctx, guid, call, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCall", reflect.TypeOf((*MockDeviceManagementFeature)(nil).ExecuteCall), ctx, guid, call, tenantID)
}

// Get mocks base method.
func (m *MockDeviceManagementFeature) Get(ctx context.Context, top, skip int, tenantID string) ([]dto.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, top, skip, tenantID)
	ret0, _ := ret[0].([]dto.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDeviceManagementFeatureMockRecorder) Get(ctx, top, skip, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeviceManagementFeature)(nil).Get), ctx, top, skip, tenantID)
}

// GetAlarmOccurrences mocks base method.
func (m *MockDeviceManagementFeature) GetAlarmOccurrences(ctx context.Context, guid string) ([]dto.AlarmClockOccurrence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlarmOccurrences", ctx, guid)
	ret0, _ := ret[0].([]dto.AlarmClockOccurrence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAlarmOccurrences indicates an expected call of GetAlarmOccurrences.
func (mr *MockDeviceManagementFeatureMockRecorder) GetAlarmOccurrences(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlarmOccurrences", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetAlarmOccurrences), ctx, guid)
}

// GetAuditLog mocks base method.
func (m *MockDeviceManagementFeature) GetAuditLog(ctx context.Context, startIndex int, guid string) (dto.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditLog", ctx, startIndex, guid)
	ret0, _ := ret[0].(dto.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditLog indicates an expected call of GetAuditLog.
func (mr *MockDeviceManagementFeatureMockRecorder) GetAuditLog(ctx, startIndex, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditLog", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetAuditLog), ctx, startIndex, guid)
}

// GetByColumn mocks base method.
func (m *MockDeviceManagementFeature) GetByColumn(ctx context.Context, columnName, queryValue, tenantId string) ([]dto.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByColumn", ctx, columnName, queryValue, tenantId)
	ret0, _ := ret[0].([]dto.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByColumn indicates an expected call of GetByColumn.
func (mr *MockDeviceManagementFeatureMockRecorder) GetByColumn(ctx, columnName, queryValue, tenantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByColumn", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetByColumn), ctx, columnName, queryValue, tenantId)
}

// GetByID mocks base method.
func (m *MockDeviceManagementFeature) GetByID(ctx context.Context, guid, tenantID string) (*dto.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, guid, tenantID)
	ret0, _ := ret[0].(*dto.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDeviceManagementFeatureMockRecorder) GetByID(ctx, guid, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetByID), ctx, guid, tenantID)
}

// GetByTags mocks base method.
func (m *MockDeviceManagementFeature) GetByTags(ctx context.Context, tags, method string, limit, offset int, tenantID string) ([]dto.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTags", ctx, tags, method, limit, offset, tenantID)
	ret0, _ := ret[0].([]dto.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTags indicates an expected call of GetByTags.
func (mr *MockDeviceManagementFeatureMockRecorder) GetByTags(ctx, tags, method, limit, offset, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTags", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetByTags), ctx, tags, method, limit, offset, tenantID)
}

// GetCertificates mocks base method.
func (m *MockDeviceManagementFeature) GetCertificates(c context.Context, guid string) (dto.SecuritySettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificates", c, guid)
	ret0, _ := ret[0].(dto.SecuritySettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCertificates indicates an expected call of GetCertificates.
func (mr *MockDeviceManagementFeatureMockRecorder) GetCertificates(c, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificates", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetCertificates), c, guid)
}

// GetCount mocks base method.
func (m *MockDeviceManagementFeature) GetCount(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCount", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCount indicates an expected call of GetCount.
func (mr *MockDeviceManagementFeatureMockRecorder) GetCount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetCount), arg0, arg1)
}

// GetDistinctTags mocks base method.
func (m *MockDeviceManagementFeature) GetDistinctTags(ctx context.Context, tenantID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctTags", ctx, tenantID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctTags indicates an expected call of GetDistinctTags.
func (mr *MockDeviceManagementFeatureMockRecorder) GetDistinctTags(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctTags", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetDistinctTags), ctx, tenantID)
}

// GetEventLog mocks base method.
func (m *MockDeviceManagementFeature) GetEventLog(ctx context.Context, guid string) ([]dto.EventLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventLog", ctx, guid)
	ret0, _ := ret[0].([]dto.EventLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventLog indicates an expected call of GetEventLog.
func (mr *MockDeviceManagementFeatureMockRecorder) GetEventLog(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventLog", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetEventLog), ctx, guid)
}

// GetExplorerSupportedCalls mocks base method.
func (m *MockDeviceManagementFeature) GetExplorerSupportedCalls() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExplorerSupportedCalls")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetExplorerSupportedCalls indicates an expected call of GetExplorerSupportedCalls.
func (mr *MockDeviceManagementFeatureMockRecorder) GetExplorerSupportedCalls() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExplorerSupportedCalls", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetExplorerSupportedCalls))
}

// GetFeatures mocks base method.
func (m *MockDeviceManagementFeature) GetFeatures(ctx context.Context, guid string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatures", ctx, guid)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatures indicates an expected call of GetFeatures.
func (mr *MockDeviceManagementFeatureMockRecorder) GetFeatures(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatures", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetFeatures), ctx, guid)
}

// GetGeneralSettings mocks base method.
func (m *MockDeviceManagementFeature) GetGeneralSettings(ctx context.Context, guid string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeneralSettings", ctx, guid)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeneralSettings indicates an expected call of GetGeneralSettings.
func (mr *MockDeviceManagementFeatureMockRecorder) GetGeneralSettings(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeneralSettings", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetGeneralSettings), ctx, guid)
}

// GetHardwareInfo mocks base method.
func (m *MockDeviceManagementFeature) GetHardwareInfo(ctx context.Context, guid string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHardwareInfo", ctx, guid)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHardwareInfo indicates an expected call of GetHardwareInfo.
func (mr *MockDeviceManagementFeatureMockRecorder) GetHardwareInfo(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHardwareInfo", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetHardwareInfo), ctx, guid)
}

// GetNetworkSettings mocks base method.
func (m *MockDeviceManagementFeature) GetNetworkSettings(c context.Context, guid string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkSettings", c, guid)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkSettings indicates an expected call of GetNetworkSettings.
func (mr *MockDeviceManagementFeatureMockRecorder) GetNetworkSettings(c, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkSettings", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetNetworkSettings), c, guid)
}

// GetPowerCapabilities mocks base method.
func (m *MockDeviceManagementFeature) GetPowerCapabilities(ctx context.Context, guid string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerCapabilities", ctx, guid)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPowerCapabilities indicates an expected call of GetPowerCapabilities.
func (mr *MockDeviceManagementFeatureMockRecorder) GetPowerCapabilities(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerCapabilities", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetPowerCapabilities), ctx, guid)
}

// GetPowerState mocks base method.
func (m *MockDeviceManagementFeature) GetPowerState(ctx context.Context, guid string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerState", ctx, guid)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPowerState indicates an expected call of GetPowerState.
func (mr *MockDeviceManagementFeatureMockRecorder) GetPowerState(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerState", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetPowerState), ctx, guid)
}

// GetUserConsentCode mocks base method.
func (m *MockDeviceManagementFeature) GetUserConsentCode(ctx context.Context, guid string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserConsentCode", ctx, guid)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserConsentCode indicates an expected call of GetUserConsentCode.
func (mr *MockDeviceManagementFeatureMockRecorder) GetUserConsentCode(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserConsentCode", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetUserConsentCode), ctx, guid)
}

// GetVersion mocks base method.
func (m *MockDeviceManagementFeature) GetVersion(ctx context.Context, guid string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, guid)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockDeviceManagementFeatureMockRecorder) GetVersion(ctx, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockDeviceManagementFeature)(nil).GetVersion), ctx, guid)
}

// Insert mocks base method.
func (m *MockDeviceManagementFeature) Insert(ctx context.Context, d *dto.Device) (*dto.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, d)
	ret0, _ := ret[0].(*dto.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockDeviceManagementFeatureMockRecorder) Insert(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockDeviceManagementFeature)(nil).Insert), ctx, d)
}

// Redirect mocks base method.
func (m *MockDeviceManagementFeature) Redirect(ctx context.Context, conn *websocket.Conn, guid, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redirect", ctx, conn, guid, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Redirect indicates an expected call of Redirect.
func (mr *MockDeviceManagementFeatureMockRecorder) Redirect(ctx, conn, guid, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redirect", reflect.TypeOf((*MockDeviceManagementFeature)(nil).Redirect), ctx, conn, guid, mode)
}

// SendConsentCode mocks base method.
func (m *MockDeviceManagementFeature) SendConsentCode(ctx context.Context, code dto.UserConsent, guid string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConsentCode", ctx, code, guid)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendConsentCode indicates an expected call of SendConsentCode.
func (mr *MockDeviceManagementFeatureMockRecorder) SendConsentCode(ctx, code, guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConsentCode", reflect.TypeOf((*MockDeviceManagementFeature)(nil).SendConsentCode), ctx, code, guid)
}

// SendPowerAction mocks base method.
func (m *MockDeviceManagementFeature) SendPowerAction(ctx context.Context, guid string, action int) (power.PowerActionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPowerAction", ctx, guid, action)
	ret0, _ := ret[0].(power.PowerActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPowerAction indicates an expected call of SendPowerAction.
func (mr *MockDeviceManagementFeatureMockRecorder) SendPowerAction(ctx, guid, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPowerAction", reflect.TypeOf((*MockDeviceManagementFeature)(nil).SendPowerAction), ctx, guid, action)
}

// SetBootOptions mocks base method.
func (m *MockDeviceManagementFeature) SetBootOptions(ctx context.Context, guid string, bootSetting dto.BootSetting) (power.PowerActionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBootOptions", ctx, guid, bootSetting)
	ret0, _ := ret[0].(power.PowerActionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBootOptions indicates an expected call of SetBootOptions.
func (mr *MockDeviceManagementFeatureMockRecorder) SetBootOptions(ctx, guid, bootSetting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBootOptions", reflect.TypeOf((*MockDeviceManagementFeature)(nil).SetBootOptions), ctx, guid, bootSetting)
}

// SetFeatures mocks base method.
func (m *MockDeviceManagementFeature) SetFeatures(ctx context.Context, guid string, features dto.Features) (dto.Features, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFeatures", ctx, guid, features)
	ret0, _ := ret[0].(dto.Features)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetFeatures indicates an expected call of SetFeatures.
func (mr *MockDeviceManagementFeatureMockRecorder) SetFeatures(ctx, guid, features any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFeatures", reflect.TypeOf((*MockDeviceManagementFeature)(nil).SetFeatures), ctx, guid, features)
}

// Update mocks base method.
func (m *MockDeviceManagementFeature) Update(ctx context.Context, d *dto.Device) (*dto.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, d)
	ret0, _ := ret[0].(*dto.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDeviceManagementFeatureMockRecorder) Update(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceManagementFeature)(nil).Update), ctx, d)
}
