// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/wificonfigs/interfaces.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/wificonfigs/interfaces.go -package v1 -mock_names Repository=MockWiFiConfigsRepository,Feature=MockWiFiConfigsFeature
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	entity "github.com/open-amt-cloud-toolkit/console/internal/entity"
	dto "github.com/open-amt-cloud-toolkit/console/internal/entity/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockWiFiConfigsRepository is a mock of Repository interface.
type MockWiFiConfigsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWiFiConfigsRepositoryMockRecorder
}

// MockWiFiConfigsRepositoryMockRecorder is the mock recorder for MockWiFiConfigsRepository.
type MockWiFiConfigsRepositoryMockRecorder struct {
	mock *MockWiFiConfigsRepository
}

// NewMockWiFiConfigsRepository creates a new mock instance.
func NewMockWiFiConfigsRepository(ctrl *gomock.Controller) *MockWiFiConfigsRepository {
	mock := &MockWiFiConfigsRepository{ctrl: ctrl}
	mock.recorder = &MockWiFiConfigsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWiFiConfigsRepository) EXPECT() *MockWiFiConfigsRepositoryMockRecorder {
	return m.recorder
}

// CheckProfileExists mocks base method.
func (m *MockWiFiConfigsRepository) CheckProfileExists(ctx context.Context, profileName, tenantID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProfileExists", ctx, profileName, tenantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProfileExists indicates an expected call of CheckProfileExists.
func (mr *MockWiFiConfigsRepositoryMockRecorder) CheckProfileExists(ctx, profileName, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProfileExists", reflect.TypeOf((*MockWiFiConfigsRepository)(nil).CheckProfileExists), ctx, profileName, tenantID)
}

// Delete mocks base method.
func (m *MockWiFiConfigsRepository) Delete(ctx context.Context, profileName, tenantID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, profileName, tenantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockWiFiConfigsRepositoryMockRecorder) Delete(ctx, profileName, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWiFiConfigsRepository)(nil).Delete), ctx, profileName, tenantID)
}

// Get mocks base method.
func (m *MockWiFiConfigsRepository) Get(ctx context.Context, top, skip int, tenantID string) ([]entity.WirelessConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, top, skip, tenantID)
	ret0, _ := ret[0].([]entity.WirelessConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWiFiConfigsRepositoryMockRecorder) Get(ctx, top, skip, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWiFiConfigsRepository)(nil).Get), ctx, top, skip, tenantID)
}

// GetByName mocks base method.
func (m *MockWiFiConfigsRepository) GetByName(ctx context.Context, guid, tenantID string) (*entity.WirelessConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, guid, tenantID)
	ret0, _ := ret[0].(*entity.WirelessConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockWiFiConfigsRepositoryMockRecorder) GetByName(ctx, guid, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockWiFiConfigsRepository)(nil).GetByName), ctx, guid, tenantID)
}

// GetCount mocks base method.
func (m *MockWiFiConfigsRepository) GetCount(ctx context.Context, tenantID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCount", ctx, tenantID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCount indicates an expected call of GetCount.
func (mr *MockWiFiConfigsRepositoryMockRecorder) GetCount(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockWiFiConfigsRepository)(nil).GetCount), ctx, tenantID)
}

// Insert mocks base method.
func (m *MockWiFiConfigsRepository) Insert(ctx context.Context, p *entity.WirelessConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, p)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockWiFiConfigsRepositoryMockRecorder) Insert(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockWiFiConfigsRepository)(nil).Insert), ctx, p)
}

// Update mocks base method.
func (m *MockWiFiConfigsRepository) Update(ctx context.Context, p *entity.WirelessConfig) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWiFiConfigsRepositoryMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWiFiConfigsRepository)(nil).Update), ctx, p)
}

// MockWiFiConfigsFeature is a mock of Feature interface.
type MockWiFiConfigsFeature struct {
	ctrl     *gomock.Controller
	recorder *MockWiFiConfigsFeatureMockRecorder
}

// MockWiFiConfigsFeatureMockRecorder is the mock recorder for MockWiFiConfigsFeature.
type MockWiFiConfigsFeatureMockRecorder struct {
	mock *MockWiFiConfigsFeature
}

// NewMockWiFiConfigsFeature creates a new mock instance.
func NewMockWiFiConfigsFeature(ctrl *gomock.Controller) *MockWiFiConfigsFeature {
	mock := &MockWiFiConfigsFeature{ctrl: ctrl}
	mock.recorder = &MockWiFiConfigsFeatureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWiFiConfigsFeature) EXPECT() *MockWiFiConfigsFeatureMockRecorder {
	return m.recorder
}

// CheckProfileExists mocks base method.
func (m *MockWiFiConfigsFeature) CheckProfileExists(ctx context.Context, profileName, tenantID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProfileExists", ctx, profileName, tenantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProfileExists indicates an expected call of CheckProfileExists.
func (mr *MockWiFiConfigsFeatureMockRecorder) CheckProfileExists(ctx, profileName, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProfileExists", reflect.TypeOf((*MockWiFiConfigsFeature)(nil).CheckProfileExists), ctx, profileName, tenantID)
}

// Delete mocks base method.
func (m *MockWiFiConfigsFeature) Delete(ctx context.Context, profileName, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, profileName, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWiFiConfigsFeatureMockRecorder) Delete(ctx, profileName, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWiFiConfigsFeature)(nil).Delete), ctx, profileName, tenantID)
}

// Get mocks base method.
func (m *MockWiFiConfigsFeature) Get(ctx context.Context, top, skip int, tenantID string) ([]dto.WirelessConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, top, skip, tenantID)
	ret0, _ := ret[0].([]dto.WirelessConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWiFiConfigsFeatureMockRecorder) Get(ctx, top, skip, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWiFiConfigsFeature)(nil).Get), ctx, top, skip, tenantID)
}

// GetByName mocks base method.
func (m *MockWiFiConfigsFeature) GetByName(ctx context.Context, guid, tenantID string) (*dto.WirelessConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, guid, tenantID)
	ret0, _ := ret[0].(*dto.WirelessConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockWiFiConfigsFeatureMockRecorder) GetByName(ctx, guid, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockWiFiConfigsFeature)(nil).GetByName), ctx, guid, tenantID)
}

// GetCount mocks base method.
func (m *MockWiFiConfigsFeature) GetCount(ctx context.Context, tenantID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCount", ctx, tenantID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCount indicates an expected call of GetCount.
func (mr *MockWiFiConfigsFeatureMockRecorder) GetCount(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockWiFiConfigsFeature)(nil).GetCount), ctx, tenantID)
}

// Insert mocks base method.
func (m *MockWiFiConfigsFeature) Insert(ctx context.Context, p *dto.WirelessConfig) (*dto.WirelessConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, p)
	ret0, _ := ret[0].(*dto.WirelessConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockWiFiConfigsFeatureMockRecorder) Insert(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockWiFiConfigsFeature)(nil).Insert), ctx, p)
}

// Update mocks base method.
func (m *MockWiFiConfigsFeature) Update(ctx context.Context, p *dto.WirelessConfig) (*dto.WirelessConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(*dto.WirelessConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWiFiConfigsFeatureMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWiFiConfigsFeature)(nil).Update), ctx, p)
}
